const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('studio', {
  chooseMedia: () => ipcRenderer.invoke('choose-media'),
  chooseRecordingMedia: () => ipcRenderer.invoke('choose-recording-media'),
  chooseOpenClawCommand: () => ipcRenderer.invoke('choose-openclaw-command'),
  beginRecordingFile: (payload) => ipcRenderer.invoke('begin-recording-file', payload),
  appendRecordingChunk: (payload) => ipcRenderer.invoke('append-recording-chunk', payload),
  finishRecordingFile: (payload) => ipcRenderer.invoke('finish-recording-file', payload),
  transcribeMedia: (options) => ipcRenderer.invoke('transcribe-media', options),
  stopTranscription: (jobId) => ipcRenderer.invoke('stop-transcription', jobId),
  openPath: (targetPath) => ipcRenderer.invoke('open-path', targetPath),
  showInFolder: (targetPath) => ipcRenderer.invoke('show-in-folder', targetPath),
  renamePath: (payload) => ipcRenderer.invoke('rename-path', payload),
  restoreMainWindow: () => ipcRenderer.invoke('restore-main-window'),
  appInfo: () => ipcRenderer.invoke('app-info'),
  checkOpenClaw: (options) => ipcRenderer.invoke('check-openclaw', options),
  testOpenClaw: (options) => ipcRenderer.invoke('test-openclaw', options),
  checkLocalAi: (options) => ipcRenderer.invoke('check-local-ai', options),
  testLocalAi: (options) => ipcRenderer.invoke('test-local-ai', options),
  checkCloudAi: (options) => ipcRenderer.invoke('check-cloud-ai', options),
  testCloudAi: (options) => ipcRenderer.invoke('test-cloud-ai', options),
  copyText: (text) => ipcRenderer.invoke('copy-text', text),
  showRecordingWidget: () => ipcRenderer.invoke('show-recording-widget'),
  hideRecordingWidget: () => ipcRenderer.invoke('hide-recording-widget'),
  showRecordingFrame: () => ipcRenderer.invoke('show-recording-frame'),
  hideRecordingFrame: () => ipcRenderer.invoke('hide-recording-frame'),
  getRecordingFrame: () => ipcRenderer.invoke('get-recording-frame'),
  recordingFrameCommand: (command) => ipcRenderer.invoke('recording-frame-command', command),
  onRecordingFrameMode: (handler) => ipcRenderer.on('recording-frame-mode', (_event, mode) => handler(mode)),
  nativeRecorderAvailable: () => ipcRenderer.invoke('native-recorder-available'),
  startNativeRecording: (options) => ipcRenderer.invoke('start-native-recording', options),
  stopNativeRecording: () => ipcRenderer.invoke('stop-native-recording'),
  mergeRecordingSegments: (payload) => ipcRenderer.invoke('merge-recording-segments', payload),
  recordingControl: (command) => ipcRenderer.invoke('recording-control', command),
  recordingWidgetState: (state) => ipcRenderer.invoke('recording-widget-state', state),
  onJobLog: (handler) => ipcRenderer.on('job-log', (_event, payload) => handler(payload)),
  onJobProgress: (handler) => ipcRenderer.on('job-progress', (_event, payload) => handler(payload)),
  onRecordingControl: (handler) => ipcRenderer.on('recording-control', (_event, command) => handler(command)),
  onRecordingState: (handler) => ipcRenderer.on('recording-state', (_event, state) => handler(state)),
  onNativeRecordingEvent: (handler) => ipcRenderer.on('native-recording-event', (_event, payload) => handler(payload))
});
